version: '2'
services:
  hutchbase-build:
    image: dockerimages.fhcrc.org/hutchbase-build:latest

    labels:
      io.rancher.container.pull_image: always

    restart: always

    secrets:
      - HUTCHBASE_BUILD_AZP_URL
      - HUTCHBASE_BUILD_AZP_TOKEN
      - HUTCHBASE_BUILD_AZP_AGENT_NAME

secrets:
  HUTCHBASE_BUILD_AZP_URL:
    external: true
  HUTCHBASE_BUILD_AZP_TOKEN:
    external: true
  HUTCHBASE_BUILD_AZP_AGENT_NAME:
    external: true
